# Generated by Django 2.1.5 on 2019-01-29 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Client Block',
                'verbose_name_plural': 'Client Blocks',
            },
        ),
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('image', models.ImageField(height_field='height_field', upload_to='clients', verbose_name='Image', width_field='width_field')),
                ('height_field', models.IntegerField(null=True, verbose_name='Height')),
                ('width_field', models.IntegerField(null=True, verbose_name='Width')),
                ('alt', models.CharField(blank=True, max_length=100, verbose_name='Image alt')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Client Item',
                'verbose_name_plural': 'Client Items',
            },
        ),
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('button_name', models.CharField(max_length=50, verbose_name='Button Name')),
                ('file', models.FileField(upload_to='download', verbose_name='File')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Icon', verbose_name='Icon')),
                ('social_links', models.ManyToManyField(blank=True, to='base.Social', verbose_name='Social Links')),
            ],
            options={
                'verbose_name': 'Downloader',
                'verbose_name_plural': 'Downloaders',
            },
        ),
        migrations.CreateModel(
            name='FactBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Fact Block',
                'verbose_name_plural': 'Fact Blocks',
            },
        ),
        migrations.CreateModel(
            name='FactItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Fact Item',
                'verbose_name_plural': 'Fact Items',
            },
        ),
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('video', 'Video'), ('particles', 'Particles'), ('image', 'Image'), ('color', 'Color')], max_length=10, verbose_name='Background Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='background', verbose_name='Image')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='Color')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'Home Background',
                'verbose_name_plural': 'Home Backgrounds',
            },
        ),
        migrations.CreateModel(
            name='PricingBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Pricing Block',
                'verbose_name_plural': 'Pricing Blocks',
            },
        ),
        migrations.CreateModel(
            name='PricingElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('excluded', models.BooleanField(verbose_name='Excluded')),
                ('new', models.BooleanField(verbose_name='New')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Pricing Element',
                'verbose_name_plural': 'Pricing Elements',
            },
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('button_name', models.CharField(blank=True, max_length=50, verbose_name='Button Name')),
                ('button_url', models.URLField(blank=True, verbose_name='Button URL')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Currency', verbose_name='Currency')),
                ('elements', models.ManyToManyField(blank=True, to='blocks.PricingElement', verbose_name='Elements')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Pricing Item',
                'verbose_name_plural': 'Pricing Items',
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Service Block',
                'verbose_name_plural': 'Service Blocks',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
            },
        ),
        migrations.CreateModel(
            name='SideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='background', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Side Image',
                'verbose_name_plural': 'Side Images',
            },
        ),
        migrations.CreateModel(
            name='SideMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, unique=True, verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Side Map',
                'verbose_name_plural': 'Side Maps',
            },
        ),
        migrations.CreateModel(
            name='SkillBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Skill Block',
                'verbose_name_plural': 'Skill Blocks',
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
            },
        ),
        migrations.CreateModel(
            name='TimelineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Timeline Block',
                'verbose_name_plural': 'Timeline Blocks',
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='Place')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Timeline Item',
                'verbose_name_plural': 'Timeline Items',
            },
        ),
        migrations.CreateModel(
            name='TypingTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_title', models.CharField(max_length=100, unique=True, verbose_name='Typing Title')),
            ],
            options={
                'verbose_name': 'Typing Title',
                'verbose_name_plural': 'Typing Titles',
            },
        ),
        migrations.AddField(
            model_name='timelineblock',
            name='timeline_items',
            field=models.ManyToManyField(to='blocks.TimelineItem', verbose_name='Timeline Items'),
        ),
        migrations.AddField(
            model_name='skillblock',
            name='skill_items',
            field=models.ManyToManyField(to='blocks.SkillItem', verbose_name='Skill Items'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service_items',
            field=models.ManyToManyField(to='blocks.ServiceItem', verbose_name='Service Items'),
        ),
        migrations.AddField(
            model_name='pricingblock',
            name='pricing_items',
            field=models.ManyToManyField(to='blocks.PricingItem', verbose_name='Pricing Items'),
        ),
        migrations.AddField(
            model_name='factblock',
            name='fact_items',
            field=models.ManyToManyField(to='blocks.FactItem', verbose_name='Fact Items'),
        ),
        migrations.AddField(
            model_name='clientblock',
            name='client_items',
            field=models.ManyToManyField(to='blocks.ClientItem', verbose_name='Client Items'),
        ),
    ]
