# Generated by Django 2.1.5 on 2019-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebackground',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('image', 'Image'), ('particles', 'Particles'), ('video', 'Video')], max_length=10, verbose_name='Background Type'),
        ),
    ]
