# Generated by Django 2.1.5 on 2019-02-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20190203_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebackground',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('particles', 'Particles'), ('video', 'Video'), ('image', 'Image')], max_length=10, verbose_name='Background Type'),
        ),
    ]
