# Generated by Django 2.1.5 on 2019-01-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g.: US Dollar, For the full list: https://www.xe.com/symbols.php', max_length=50, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='e.g.: USD', max_length=3, unique=True, verbose_name='Code')),
                ('symbol', models.CharField(help_text='e.g.: $', max_length=1, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='find icon from the link: https://icons8.com/line-awesome  and paste the code', max_length=50, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English')], max_length=50, verbose_name='Language')),
                ('right_to_left', models.BooleanField(verbose_name='Right To Left')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=320, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=100, verbose_name='Keywords')),
                ('logo', models.CharField(blank=True, max_length=1, verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon', verbose_name='Favicon')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('theme_color', models.CharField(choices=[('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], max_length=50, verbose_name='Theme Color')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_on_header',
            field=models.ManyToManyField(blank=True, to='base.Social', verbose_name='Social On Header'),
        ),
    ]
