# Generated by Django 2.1.5 on 2019-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='theme_color',
            field=models.CharField(choices=[('pink', 'Pink'), ('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('purple', 'Purple')], max_length=50, verbose_name='Theme Color'),
        ),
    ]
