# Generated by Django 2.1.5 on 2019-02-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190203_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='theme_color',
            field=models.CharField(choices=[('orange', 'Orange'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple'), ('blue', 'Blue'), ('red', 'Red')], max_length=50, verbose_name='Theme Color'),
        ),
    ]
