apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: portfolio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: portfolio
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: portfolio
            - secretRef:
                name: portfolio
