apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    {{- include "movies.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/instance: {{ .Release.Name }}
