# Generated by Django 2.1.5 on 2019-01-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g.: Home, About, Resume, Portfolio, Blog, Contacts', max_length=50, unique=True, verbose_name='Name')),
                ('route', models.CharField(max_length=50, unique=True, verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Head',
                'verbose_name_plural': 'Heads',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('head_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Head')),
                ('title_name', models.CharField(blank=True, max_length=100, verbose_name='Title Name')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtitle')),
                ('background_title', models.CharField(blank=True, max_length=8, verbose_name='Background Title')),
                ('side', models.CharField(blank=True, choices=[('map', 'Map'), ('image', 'Image')], max_length=50, verbose_name='Side')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='Last Modify')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blocks.HomeBackground', verbose_name='Background')),
                ('client_blocks', models.ManyToManyField(blank=True, to='blocks.ClientBlock', verbose_name='Client Blocks')),
                ('downloader', models.ManyToManyField(blank=True, to='blocks.Downloader', verbose_name='Downloader')),
                ('fact_blocks', models.ManyToManyField(blank=True, to='blocks.FactBlock', verbose_name='Fact Blocks')),
                ('pricing_blocks', models.ManyToManyField(blank=True, to='blocks.PricingBlock', verbose_name='Pricing Blocks')),
                ('service_blocks', models.ManyToManyField(blank=True, to='blocks.ServiceBlock', verbose_name='Service Blocks')),
                ('side_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blocks.SideImage', verbose_name='Side Image')),
                ('side_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blocks.SideMap', verbose_name='Side Map')),
                ('skill_blocks', models.ManyToManyField(blank=True, to='blocks.SkillBlock', verbose_name='Skill Blocks')),
                ('timeline_blocks', models.ManyToManyField(blank=True, to='blocks.TimelineBlock', verbose_name='Timeline Blocks')),
                ('typing_title', models.ManyToManyField(blank=True, to='blocks.TypingTitle', verbose_name='Typing Title')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=('pages.head',),
        ),
        migrations.AddField(
            model_name='head',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Icon', verbose_name='Icon'),
        ),
    ]
