# Generated by Django 3.2.16 on 2022-12-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='side',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('map', 'Map')], max_length=50, verbose_name='Side'),
        ),
    ]
