apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: PORTFOLIO_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
        envFrom:
          - configMapRef:
              name: portfolio
          # - secretRef:
          #     name: portfolio
        env:
        - name: DJ_SECRET_KEY
          value: "${{ DJ_SECRET_KEY }}"
        - name: DB_NAME
          value: "${{ DB_NAME }}"
        - name: DB_USERNAME
          value: "${{ DB_USERNAME }}"
        - name: DB_PASSWORD
          value: "${{ DB_PASSWORD }}"
        - name: AWS_ACCESS_KEY_ID
          value: "${{ AWS_ACCESS_KEY_ID }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "${{ AWS_SECRET_ACCESS_KEY }}"
