apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
configMapGenerator:
- behavior: create
  envs:
  - config/django.env
  - config/database.env
  - config/objects.env
  name: portfolio
# secretGenerator:
# - behavior: create
#   envs:
#   - test.env
#   name: portfolio
# secretGenerator:
# - behavior: create
#   envs:
#   - secrets/django.env
#   - secrets/database.env
#   - secrets/objects.env
#   name: portfolio
images:
- digest: sha256:a9024a7ab62d3e02653349306cbc36881bd3a94b3dfc77dbd7ba11b6046b6289
  name: PORTFOLIO_IMAGE
  newName: registry.cloud.okteto.net/hosamalmoghraby/porfolio-django-portfolio
