apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
configMapGenerator:
- behavior: create
  envs:
  - config.env
  name: portfolio
secretGenerator:
- behavior: create
  envs:
  - secrets.env
  name: portfolio
images:
- digest: sha256:0a061db17b3e92fbcbc6587396325402939b12c0cdef873257b44d534f94c2d0
  name: PORTFOLIO_IMAGE
  newName: registry.cloud.okteto.net/hosamalmoghraby/porfolio-django-portfolio
