apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
configMapGenerator:
- behavior: create
  envs:
  - app.config
  name: portfolio
secretGenerator:
- behavior: create
  envs:
  - secrets.env
  name: portfolio
images:
- digest: sha256:d6d8ce56c39bedb0656724f0fdf3cd072db2ea5888d1123679d1472a63c62a1c
  name: PORTFOLIO_IMAGE
  newName: registry.cloud.okteto.net/test-hosamalmoghraby/porfolio-django-portfolio
