on:
  push:
    branches:
      - development

name: Deploy Development Environment

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ vars.OKTETO_URL }}

      - name: Deploy development environment
        uses: okteto/pipeline@latest
        with:
          name: portfolio
          variables: "
            DJ_SECRET_KEY=${{ secrets.DJ_SECRET_KEY }},
            DB_USERNAME=${{ secrets.DB_USERNAME }},
            DB_PASSWORD=${{ secrets.DB_PASSWORD }},
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            "
