on:
  push:
    branches:
      - development

name: Deploy Development Environment

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ secrets.OKTETO_URL }}

      - name: Development namespace
        uses: okteto/create-namespace@latest
        with:
          namespace: portfolio-${{ secrets.OKTETO_USERNAME }}

      - name: Deploy development environment
        uses: okteto/pipeline@latest
        with:
          name: portfolio
          variables: "
            DJ_DEBUG_MODE=${{ secrets.DJ_DEBUG_MODE }},
            DJ_ALLOWED_HOSTS=${{ secrets.DJ_ALLOWED_HOSTS }},
            DJ_LANGUAGE_CODE=${{ secrets.DJ_LANGUAGE_CODE }},
            DJ_TIME_ZONE=${{ secrets.DJ_TIME_ZONE }},
            DJ_USE_I18N=${{ secrets.DJ_USE_I18N }},
            DJ_USE_TZ=${{ secrets.DJ_USE_TZ }}
            "
