on:
  pull_request:
    branches:
      - development

name: Deploy Preview Environment

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ vars.OKTETO_URL }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-${{ vars.OKTETO_USERNAME }}
          scope: personal
          variables: "
            DJ_SECRET_KEY=${{ secrets.DJ_SECRET_KEY }},
            DB_USERNAME=${{ secrets.DB_USERNAME }},
            DB_PASSWORD=${{ secrets.DB_PASSWORD }},
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            "
