on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types:
      - closed

name: Deploy Development Environment

jobs:
  deploy_development:
    runs-on: ubuntu-latest
    steps:
      # - name: Context
      #   uses: okteto/context@latest
      #   with:
      #     token: ${{ secrets.OKTETO_TOKEN }}
      #     url: ${{ secrets.OKTETO_URL }}

      - name: Activate namespace
        uses: okteto/create-namespace@latest
        with:
          namespace: development-hosamalmoghraby

      # - name: Deploy development environment
      #   uses: okteto/pipeline@latest
      #   with:
      #     name: development-hosamalmoghraby
      #     scope: personal
