on:
  workflow_dispatch:

name: Destroy Development Environment

jobs:
  destroy_development:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ secrets.OKTETO_URL }}

      - name: Destroy Development namespace
        uses: okteto/delete-namespace@latest
        with:
          namespace: development-hosamalmoghraby
