on:
  pull_request:
    types:
      - closed

name: Destroy Preview Environment

jobs:
  destroy_preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          url: ${{ vars.OKTETO_URL }}

      - name: Destroy preview environment
        uses: okteto/destroy-preview@latest
        with:
          name: pr-${{ github.event.number }}-${{ vars.OKTETO_USERNAME }}
